# Generated by Django 5.0 on 2025-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
    ]
